name: flutter_app_template
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

workspace:
  - app_lib/database
  - app_lib/gamepad
  - app_lib/theme
  - app_lib/locale
  - app_lib/provider
  - app_lib/logging
  - app_lib/secure_storage
  - app_bloc/gamepad
  - app_bloc/navigation
  - app_bloc/theme
  - app_widget/adaptive
  - app_widget/artwork
  - app_widget/feedback
  - app_widget/web_view
  - app_form/demo
  - app_plugin/client_info/client_info
  - app_plugin/client_info/client_info_platform_interface
  - app_plugin/client_info/client_info_android
  - app_plugin/client_info/client_info_ios
  - app_plugin/client_info/client_info_linux
  - app_plugin/client_info/client_info_macos
  - app_plugin/client_info/client_info_windows
  - third_party/form_bloc
  - third_party/flutter_form_bloc
  - third_party/flutter_adaptive_scaffold
  - third_party/settings_ui

dependencies:
  flutter:
    sdk: flutter

  logging: ^1.3.0

  go_router: ^17.0.1

  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  provider: ^6.1.5
  equatable: ^2.0.7

  shared_preferences: ^2.3.5
  path_provider: ^2.1.5
  path: any

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  lottie: ^3.3.1
  google_fonts: ^6.2.1

  # workspace packages
  app_database: any
  app_gamepad: any
  app_theme: any
  app_locale: any
  app_provider: any
  gamepad_bloc: any
  nav_bloc: any
  theme_bloc: any
  app_artwork: any
  app_client_info: any
  app_feedback: any
  app_adaptive_widgets: any
  settings_ui: any
  app_logging: any
  app_secure_storage: any
  app_web_view: any
  demo_form: any
  flutter_form_bloc: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.26.3

  flutter_lints: ^6.0.0

  build_runner: ^2.4.15

  melos: ^7.0.0
  mason: ^0.1.1
  mason_cli: ^0.1.1
  dependency_validator: ^5.0.2

flutter:
  uses-material-design: true

# generate icon with :
# > dart pub global activate flutter_launcher_icons
# > dart pub global run flutter_launcher_icons
flutter_launcher_icons:
  image_path: "app_widget/artwork/assets/icon/app-icon.png"
  android: true
  ios: true
  min_sdk_android: 21
  windows:
    generate: true
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true

melos:
  name: flutter_app_template
  command:
    version:
      # Only allow versioning to happen on main branch.
      branch: main
      # Generates a link to a prefilled GitHub release creation page.
      releaseUrl: true

  scripts:
    prepare:
      description: Prepare project with `bootstrap`, `build_runner build` and `gen-l10n`
      steps:
        - melos bootstrap
        - melos run gen-l10n
        - melos run build-runner

    build-runner:
      run: dart run build_runner build --delete-conflicting-outputs
      exec:
        orderDependents: true
      description: Run `dart/flutter analyze` for all packages.

    analyze:
      description: Run `dart/flutter analyze` for all packages.
      steps:
        - melos run analyze:dart
        - melos run analyze:flutter

    analyze:dart:
      run: dart analyze --fatal-warnings
      exec:
        concurrency: 1
        orderDependents: true
      packageFilters:
        flutter: false
      description: Run `dart analyze` for non-Flutter packages.

    analyze:flutter:
      run: flutter analyze --fatal-warnings
      exec:
        concurrency: 1
        orderDependents: true
      packageFilters:
        flutter: true
      description: Run `flutter analyze` for Flutter packages.

    fix:
      run: dart fix . --apply
      exec:
        orderDependents: true
      description: Run `dart fix` for all packages.

    fix-dry-run:
      run: dart fix . --dry-run
      exec:
        orderDependents: true
      description: Run `dart fix` in dry-run mode for all packages.

    format:
      run: dart format .
      exec:
        orderDependents: true
      description: Run `dart format` for all packages.

    format-check:
      run: dart format . --set-exit-if-changed
      exec:
        orderDependents: true
      description: Run `dart format` checks for all packages.

    upgrade:
      run: dart pub upgrade --major-versions
      exec:
        orderDependents: true
      description: Run `flutter pub upgrade` update dependencies in all packages.

    outdated:
      run: dart pub outdated
      exec:
        orderDependents: true
      description: Run `flutter pub outdated` check outdated dependencies in all packages.

    validate-dependencies:
      run: dart run dependency_validator
      description: Run `dart run dependency_validator` check dependencies usage.

    test:
      run: melos exec --order-dependents --fail-fast flutter test || true
      description: Run Flutter tests for all packages (ignores packages without tests).
      steps:
        - melos run test:dart
        - melos run test:flutter

    test:dart:
      run: dart test
      exec:
        orderDependents: true
        fail-fast: true
      packageFilters:
        flutter: false
        dirExists: test

    test:flutter:
      run: flutter test
      exec:
        orderDependents: true
        fail-fast: true
      packageFilters:
        flutter: true
        dirExists: test

    gen-l10n:
      run: flutter gen-l10n
      exec:
        orderDependents: true
      packageFilters:
        flutter: true
        fileExists: l10n.yaml
      description: Generate localization files from ARB files.

