name: nav_bloc
description: App navigation bloc for managing navigation state
version: 1.0.0

environment:
  sdk: ">=3.8.0 <4.0.0"
resolution: workspace

dependencies:
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  go_router: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
